// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-y2x3I7vGe4g4O8hpFbCJTvF3cEJVfoo',
    appId: '1:451596383368:web:1aeec6af76c82d2e90db3d',
    messagingSenderId: '451596383368',
    projectId: 'doit-277bb',
    authDomain: 'doit-277bb.firebaseapp.com',
    storageBucket: 'doit-277bb.firebasestorage.app',
    measurementId: 'G-51C93DJ447',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMN5d2nCY7yK349iETW9bwwMvrKsO7xZU',
    appId: '1:451596383368:android:e9edc1f0c27aca8290db3d',
    messagingSenderId: '451596383368',
    projectId: 'doit-277bb',
    storageBucket: 'doit-277bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH0gJhR_l4kidc8ZUfg-E5QQLEVUbvivI',
    appId: '1:451596383368:ios:8464bf361c71d24f90db3d',
    messagingSenderId: '451596383368',
    projectId: 'doit-277bb',
    storageBucket: 'doit-277bb.firebasestorage.app',
    iosClientId: '451596383368-5o47bargiot50h30s490u2bqr77lsfm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoappp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH0gJhR_l4kidc8ZUfg-E5QQLEVUbvivI',
    appId: '1:451596383368:ios:8464bf361c71d24f90db3d',
    messagingSenderId: '451596383368',
    projectId: 'doit-277bb',
    storageBucket: 'doit-277bb.firebasestorage.app',
    iosClientId: '451596383368-5o47bargiot50h30s490u2bqr77lsfm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoappp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-y2x3I7vGe4g4O8hpFbCJTvF3cEJVfoo',
    appId: '1:451596383368:web:0c27c0abd624156290db3d',
    messagingSenderId: '451596383368',
    projectId: 'doit-277bb',
    authDomain: 'doit-277bb.firebaseapp.com',
    storageBucket: 'doit-277bb.firebasestorage.app',
    measurementId: 'G-5HSZZBPZLS',
  );
}
